cat pages/home.md > index.md 
cat pages/publications.md > index.md 
cat pages/publications.md >> index.md 
cat pages/home.md > index.md 
cat pages/publications.md >> index.md 
cat pages/setup.md >> index.md 
cat pages/sgx-sdk-setup.md >> index.md 
cat pages/panoply-demo.md >> index.md 
cat pages/faq.md >> index.md 
cat pages/contact.md >> index.md 
cat pages/ack.md >> index.md 