copy ssl\dtls1.h include\openssl\dtls1.h
copy ssl\kssl.h include\openssl\kssl.h
copy ssl\srtp.h include\openssl\srtp.h
copy ssl\ssl23.h include\openssl\ssl23.h
copy ssl\ssl2.h include\openssl\ssl2.h
copy ssl\ssl3.h include\openssl\ssl3.h
copy ssl\ssl.h include\openssl\ssl.h
copy ssl\tls1.h include\openssl\tls1.h
copy crypto\cmac\cmac.h include\openssl\cmac.h
copy crypto\srp\srp.h include\openssl\srp.h
copy crypto\ts\ts.h include\openssl\ts.h
copy crypto\pqueue\pqueue.h include\openssl\pqueue.h
copy crypto\cms\cms.h include\openssl\cms.h
copy crypto\krb5\krb5_asn.h include\openssl\krb5_asn.h
copy crypto\ui\ui_compat.h include\openssl\ui_compat.h
copy crypto\ui\ui.h include\openssl\ui.h
copy crypto\ocsp\ocsp.h include\openssl\ocsp.h
copy crypto\comp\comp.h include\openssl\comp.h
copy crypto\pkcs12\pkcs12.h include\openssl\pkcs12.h
copy crypto\pkcs7\pkcs7.h include\openssl\pkcs7.h
copy crypto\txt_db\txt_db.h include\openssl\txt_db.h
copy crypto\conf\conf_api.h include\openssl\conf_api.h
copy crypto\conf\conf.h include\openssl\conf.h
copy crypto\x509v3\x509v3.h include\openssl\x509v3.h
copy crypto\x509\x509.h include\openssl\x509.h
copy crypto\x509\x509_vfy.h include\openssl\x509_vfy.h
copy crypto\pem\pem2.h include\openssl\pem2.h
copy crypto\pem\pem.h include\openssl\pem.h
copy crypto\asn1\asn1.h include\openssl\asn1.h
copy crypto\asn1\asn1_mac.h include\openssl\asn1_mac.h
copy crypto\asn1\asn1t.h include\openssl\asn1t.h
copy crypto\evp\evp.h include\openssl\evp.h
copy crypto\err\err.h include\openssl\err.h
copy crypto\rand\rand.h include\openssl\rand.h
copy crypto\lhash\lhash.h include\openssl\lhash.h
copy crypto\stack\safestack.h include\openssl\safestack.h
copy crypto\stack\stack.h include\openssl\stack.h
copy crypto\bio\bio.h include\openssl\bio.h
copy crypto\buffer\buffer.h include\openssl\buffer.h
copy crypto\engine\engine.h include\openssl\engine.h
copy crypto\dso\dso.h include\openssl\dso.h
copy crypto\ecdh\ecdh.h include\openssl\ecdh.h
copy crypto\dh\dh.h include\openssl\dh.h
copy crypto\ecdsa\ecdsa.h include\openssl\ecdsa.h
copy crypto\dsa\dsa.h include\openssl\dsa.h
copy crypto\rsa\rsa.h include\openssl\rsa.h
copy crypto\ec\ec.h include\openssl\ec.h
copy crypto\bn\bn.h include\openssl\bn.h
copy crypto\modes\modes.h include\openssl\modes.h
copy crypto\seed\seed.h include\openssl\seed.h
copy crypto\camellia\camellia.h include\openssl\camellia.h
copy crypto\cast\cast.h include\openssl\cast.h
copy crypto\bf\blowfish.h include\openssl\blowfish.h
copy crypto\idea\idea.h include\openssl\idea.h
copy crypto\rc4\rc4.h include\openssl\rc4.h
copy crypto\rc2\rc2.h include\openssl\rc2.h
copy crypto\aes\aes.h include\openssl\aes.h
copy crypto\des\des.h include\openssl\des.h
copy crypto\des\des_old.h include\openssl\des_old.h
copy crypto\whrlpool\whrlpool.h include\openssl\whrlpool.h
copy crypto\ripemd\ripemd.h include\openssl\ripemd.h
copy crypto\hmac\hmac.h include\openssl\hmac.h
copy crypto\mdc2\mdc2.h include\openssl\mdc2.h
copy crypto\sha\sha.h include\openssl\sha.h
copy crypto\md5\md5.h include\openssl\md5.h
copy crypto\md4\md4.h include\openssl\md4.h
copy crypto\objects\objects.h include\openssl\objects.h
copy crypto\objects\obj_mac.h include\openssl\obj_mac.h
copy crypto\crypto.h include\openssl\crypto.h
copy crypto\ebcdic.h include\openssl\ebcdic.h
copy crypto\opensslconf.h include\openssl\opensslconf.h
copy crypto\opensslv.h include\openssl\opensslv.h
copy crypto\ossl_typ.h include\openssl\ossl_typ.h
copy crypto\symhacks.h include\openssl\symhacks.h
copy e_os2.h include\openssl\e_os2.h

copy crypto\store\store.h include\openssl\store.h
copy crypto\md2\md2.h include\openssl\md2.h
